controller:
  service:
    httpPort:
      targetPort: 80
    httpsPort:
      targetPort: 80
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:418272784676:certificate/127384f6-f1cc-4987-943a-aa1acbf0b477
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"