variable "env" {}
variable "instance_type" {}
variable "component_name" {}
variable "app_port" {}
variable "domain_name" {}
variable "zone_id" {}
variable "vault_token" {}
variable "volume_size" {}
variable "subnet_id" {}
variable "vpc_id" {}