name: Terraform Infra Provision
on: [workflow_dispatch]
jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          make dev-apply token="$env:vault_token"
        env:
          vault_token: ${{ secrets.vault_token }}